name: Collect BLS Data

on:
  schedule:
    # Run on the 5th day of each month at 00:00 UTC
    - cron: '0 0 5 * *'
  workflow_dispatch:
    
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run the data collection script
        env:
          BLS_API_KEY: ${{ secrets.BLS_API_KEY }}
        run: |
          python collect_data.py

      - name: Commit and push updated data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add bls_data.csv
          git commit -m "Update BLS data for new release"
          git push

